
CHARGERENABLED_SENSOR = "charger_enabled"
CHARGERDONE_SENSOR = "charger_done"
CURRENTPEAK_SENSOR = "current_peak"
TOTALHOURLYENERGY_SENSOR = "totalhourlyenergy"
CARPOWERSENSOR_SENSOR = "carpowersensor"
POWERSNSRMOVINGAVERAGE_SENSOR = "powersensormovingaverage"
POWERSNSRMOVINGAVERAGE24_SENSOR = "powersensormovingaverage24"
POWERSNSRMOVINGAVERAGE5_SENSOR = "power_sensor_moving_average_5"
POWER_SENSOR = "power"
POWER_TREND_SENSOR = "power_trend"
AMP_METER_SENSOR = "amp_meter"
CHARGEROBJECT_SENSOR = "chargerobject"
CHARGEROBJECT_SWITCH_SENSOR = "chargerobject_switch"
